module.exports = [
  { keyword: 'santander', brand: 'Banco Santander' },
  { keyword: 'bbva', brand: 'BBVA' },
  { keyword: 'caixabank', brand: 'CaixaBank' },
  { keyword: 'sabadell', brand: 'Banco Sabadell' },
  { keyword: 'bankia', brand: 'Bankia' },
  { keyword: 'unicaja', brand: 'Unicaja Banco' },
  { keyword: 'kutxabank', brand: 'Kutxabank' },
  { keyword: 'abanca', brand: 'ABANCA' },
  { keyword: 'bankinter', brand: 'Bankinter' },
  { keyword: 'iberbank', brand: 'Ibercaja' },
  { keyword: 'cajamar', brand: 'Cajamar' },
  { keyword: 'laboral', brand: 'Laboral Kutxa' },
  { keyword: 'correos', brand: 'Correos' },
  { keyword: 'seur', brand: 'SEUR' },
  { keyword: 'mrw', brand: 'MRW' },
  { keyword: 'nacex', brand: 'NACEX' },
  { keyword: 'gls', brand: 'GLS' },
  { keyword: 'zeleris', brand: 'Zeleris' },
  { keyword: 'envialia', brand: 'Envialia' },
  { keyword: 'redyser', brand: 'Redyser' },
  { keyword: 'tipsa', brand: 'TIPSA' },
  { keyword: 'asm', brand: 'ASM Transporte Urgente' },
  { keyword: 'ups', brand: 'UPS' },
  { keyword: 'dhl', brand: 'DHL' },
  { keyword: 'hacienda', brand: 'Agencia Tributaria' },
  { keyword: 'declaracion de la renta', brand: 'Agencia Tributaria' },
  { keyword: 'seguridadsocial', brand: 'Seguridad Social' },
  { keyword: 'dgt', brand: 'DGT' },
  { keyword: 'tráfico', brand: 'DGT' },
];
