module.exports = [
  { prefix: '+20', country: 'Egipto', flag: '🇪🇬' },
  { prefix: '+30', country: 'Grecia', flag: '🇬🇷' },
  { prefix: '+31', country: 'Países Bajos', flag: '🇳🇱' },
  { prefix: '+32', country: 'Bélgica', flag: '🇧🇪' },
  { prefix: '+33', country: 'Francia', flag: '🇫🇷' },
  { prefix: '+34', country: 'España', flag: '🇪🇸' },
  { prefix: '+36', country: 'Hungría', flag: '🇭🇺' },
  { prefix: '+39', country: 'Italia', flag: '🇮🇹' },
  { prefix: '+40', country: 'Rumanía', flag: '🇷🇴' },
  { prefix: '+41', country: 'Suiza', flag: '🇨🇭' },
  { prefix: '+43', country: 'Austria', flag: '🇦🇹' },
  { prefix: '+44', country: 'Reino Unido', flag: '🇬🇧' },
  { prefix: '+45', country: 'Dinamarca', flag: '🇩🇰' },
  { prefix: '+46', country: 'Suecia', flag: '🇸🇪' },
  { prefix: '+47', country: 'Noruega', flag: '🇳🇴' },
  { prefix: '+48', country: 'Polonia', flag: '🇵🇱' },
  { prefix: '+49', country: 'Alemania', flag: '🇩🇪' },
  { prefix: '+51', country: 'Perú', flag: '🇵🇪' },
  { prefix: '+52', country: 'México', flag: '🇲🇽' },
  { prefix: '+53', country: 'Cuba', flag: '🇨🇺' },
  { prefix: '+54', country: 'Argentina', flag: '🇦🇷' },
  { prefix: '+55', country: 'Brasil', flag: '🇧🇷' },
  { prefix: '+56', country: 'Chile', flag: '🇨🇱' },
  { prefix: '+57', country: 'Colombia', flag: '🇨🇴' },
  { prefix: '+58', country: 'Venezuela', flag: '🇻🇪' },
  { prefix: '+60', country: 'Malasia', flag: '🇲🇾' },
  { prefix: '+61', country: 'Australia', flag: '🇦🇺' },
  { prefix: '+62', country: 'Indonesia', flag: '🇮🇩' },
  { prefix: '+63', country: 'Filipinas', flag: '🇵🇭' },
  { prefix: '+64', country: 'Nueva Zelanda', flag: '🇳🇿' },
  { prefix: '+65', country: 'Singapur', flag: '🇸🇬' },
  { prefix: '+66', country: 'Tailandia', flag: '🇹🇭' },
  { prefix: '+81', country: 'Japón', flag: '🇯🇵' },
  { prefix: '+82', country: 'Corea del Sur', flag: '🇰🇷' },
  { prefix: '+84', country: 'Vietnam', flag: '🇻🇳' },
  { prefix: '+86', country: 'China', flag: '🇨🇳' },
  { prefix: '+90', country: 'Turquía', flag: '🇹🇷' },
  { prefix: '+91', country: 'India', flag: '🇮🇳' },
  { prefix: '+92', country: 'Pakistán', flag: '🇵🇰' },
  { prefix: '+93', country: 'Afganistán', flag: '🇦🇫' },
  { prefix: '+94', country: 'Sri Lanka', flag: '🇱🇰' },
  { prefix: '+95', country: 'Birmania', flag: '🇲🇲' },
  { prefix: '+98', country: 'Irán', flag: '🇮🇷' },
  { prefix: '+20', country: 'Egipto', flag: '🇪🇬' },
  { prefix: '+27', country: 'Sudáfrica', flag: '🇿🇦' },
  { prefix: '+30', country: 'Grecia', flag: '🇬🇷' },
  { prefix: '+32', country: 'Bélgica', flag: '🇧🇪' },
  { prefix: '+33', country: 'Francia', flag: '🇫🇷' },
  { prefix: '+34', country: 'España', flag: '🇪🇸' },
  { prefix: '+36', country: 'Hungría', flag: '🇭🇺' },
  { prefix: '+39', country: 'Italia', flag: '🇮🇹' },
  { prefix: '+40', country: 'Rumanía', flag: '🇷🇴' },
  { prefix: '+41', country: 'Suiza', flag: '🇨🇭' },
  { prefix: '+43', country: 'Austria', flag: '🇦🇹' },
  { prefix: '+44', country: 'Reino Unido', flag: '🇬🇧' },
  { prefix: '+45', country: 'Dinamarca', flag: '🇩🇰' },
  { prefix: '+46', country: 'Suecia', flag: '🇸🇪' },
  { prefix: '+47', country: 'Noruega', flag: '🇳🇴' },
  { prefix: '+48', country: 'Polonia', flag: '🇵🇱' },
  { prefix: '+49', country: 'Alemania', flag: '🇩🇪' },
];
